USE `minions`;

CREATE TABLE `minions` (
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR (50) NOT NULL,
age INT
);

CREATE TABLE `towns` (
`town_id` INT AUTO_INCREMENT PRIMARY KEY,
`name` VARCHAR (50) NOT NULL
);
